# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-01 22:19
from __future__ import unicode_literals

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
